#!/bin/sh

mjpg_width=640
mjpg_height=480

yuv_width=640
yuv_height=480
yuv_bytes_per_pixel=2

# det-dimensions.dat generated by appcore at every start
STREAM_HEIGHT=$(grep height /etc/det-dimensions.dat | awk '{print $2}')
STREAM_WIDTH=$(grep width /etc/det-dimensions.dat | awk '{print $2}')
STREAM_HEIGHT=${STREAM_HEIGHT:=348}
STREAM_WIDTH=${STREAM_WIDTH:=464}

signal_uvc_enable() {
    if [ "$(pidof streamserver)" ] ; then
        killall -USR1 streamserver 2>/dev/null;
    fi
}

signal_uvc_disable() {
    if [ "$(pidof streamserver)" ] ; then
        killall -USR2 streamserver 2>/dev/null;
    fi
}

setup_usbmode_uvc () {
    # Control endpoint packet size is 64 bytes.
    echo 0x40 > bMaxPacketSize0

    mkdir functions/uvc.usb0
    echo 16 > functions/uvc.usb0/streaming_bulk_mult

    mkdir -p functions/uvc.usb0/streaming/uncompressed/yuv/480p

    printf 'UYVY\x00\x00\x10\x00\x80\x00\x00\xaa\x00\x38\x9b\x71' > functions/uvc.usb0/streaming/uncompressed/yuv/guidFormat

    # Class-specific VS Frame Descriptor.
    echo "$yuv_width" > functions/uvc.usb0/streaming/uncompressed/yuv/480p/wWidth
    echo "$yuv_height" > functions/uvc.usb0/streaming/uncompressed/yuv/480p/wHeight

    # echo 614400 > functions/uvc.usb0/streaming/uncompressed/yuv/480p/dwMaxVideoFrameBufferSize
    echo $(( $yuv_width * $yuv_height * $yuv_bytes_per_pixel )) > functions/uvc.usb0/streaming/uncompressed/yuv/480p/dwMaxVideoFrameBufferSize

    echo 333333 > functions/uvc.usb0/streaming/uncompressed/yuv/480p/dwDefaultFrameInterval

    # Class-specifig VS Frame Descriptor.
    cat <<EOF > functions/uvc.usb0/streaming/uncompressed/yuv/480p/dwFrameInterval
333333
666666
1000000
EOF

    mkdir -p functions/uvc.usb0/streaming/mjpeg/frame/480p
    echo "$mjpg_width" > functions/uvc.usb0/streaming/mjpeg/frame/480p/wWidth
    echo "$mjpg_height" > functions/uvc.usb0/streaming/mjpeg/frame/480p/wHeight
    echo 786432 > functions/uvc.usb0/streaming/mjpeg/frame/480p/dwMaxVideoFrameBufferSize
    echo 333333 > functions/uvc.usb0/streaming/mjpeg/frame/480p/dwDefaultFrameInterval
    cat <<EOF > functions/uvc.usb0/streaming/mjpeg/frame/480p/dwFrameInterval
333333
666666
1000000
EOF

    mkdir -p functions/uvc.usb0/streaming/framebased/mjls/480p
    printf 'MJLS\x00\x00\x10\x00\x80\x00\x00\xaa\x00\x38\x9b\x71' > functions/uvc.usb0/streaming/framebased/mjls/guidFormat
    echo "${STREAM_WIDTH}" > functions/uvc.usb0/streaming/framebased/mjls/480p/wWidth
    echo "${STREAM_HEIGHT}" > functions/uvc.usb0/streaming/framebased/mjls/480p/wHeight
    echo 333333 > functions/uvc.usb0/streaming/framebased/mjls/480p/dwDefaultFrameInterval
    cat <<EOF > functions/uvc.usb0/streaming/framebased/mjls/480p/dwFrameInterval
333333
666666
1000000
EOF

    mkdir -p functions/uvc.usb0/streaming/framebased/dfvi/480p
    printf 'DFVI\x00\x00\x10\x00\x80\x00\x00\xaa\x00\x38\x9b\x71' > functions/uvc.usb0/streaming/framebased/dfvi/guidFormat
    echo "${STREAM_WIDTH}" > functions/uvc.usb0/streaming/framebased/dfvi/480p/wWidth
    echo "${STREAM_HEIGHT}" > functions/uvc.usb0/streaming/framebased/dfvi/480p/wHeight
    echo 333333 > functions/uvc.usb0/streaming/framebased/dfvi/480p/dwDefaultFrameInterval
    cat <<EOF > functions/uvc.usb0/streaming/framebased/dfvi/480p/dwFrameInterval
333333
666666
1000000
EOF

    mkdir -p functions/uvc.usb0/streaming/header/h
    cd functions/uvc.usb0/streaming/header/h || exit 1
    ln -s ../../uncompressed/yuv .
    ln -s ../../mjpeg/frame .
    ln -s ../../framebased/mjls .
    ln -s ../../framebased/dfvi .
    cd ../../class/fs || exit 1
    ln -s ../../header/h .
    cd ../../class/hs || exit 1
    ln -s ../../header/h .
    cd ../../class/ss || exit 1
    ln -s ../../header/h .
    cd ../../../control || exit 1
    mkdir header/h
    ln -s header/h class/fs
    ln -s header/h class/ss
    cd ../../../ || exit 1

    # Link everything up and bind the USB device.
    ln -s functions/uvc.usb0 configs/c.1
}