#!/bin/sh

# det-dimensions.dat generated by appcore at every start
STREAM_HEIGHT=$(awk '/height/{print $2}' /etc/det-dimensions.dat)
STREAM_WIDTH=$(awk '/width/{print $2}' /etc/det-dimensions.dat)
STREAM_HEIGHT=${STREAM_HEIGHT:=348}
STREAM_WIDTH=${STREAM_WIDTH:=464}

signal_uvc_enable() {
    if [ "$(pidof streamserver)" ] ; then
        killall -USR1 streamserver 2>/dev/null;
    fi
}

signal_uvc_disable() {
    if [ "$(pidof streamserver)" ] ; then
        killall -USR2 streamserver 2>/dev/null;
    fi
}

setup_usbmode_uvc () {
    # Inflate tar file with skeleton
    tar --overwrite --strip-components=1 -xmf /etc/gadget/uvc-sysfs-skeleton.tar

    # These are not included in the tar file since they are dynamic
    echo "${STREAM_WIDTH}" > functions/uvc.usb0/streaming/framebased/mjls/480p/wWidth
    echo "${STREAM_HEIGHT}" > functions/uvc.usb0/streaming/framebased/mjls/480p/wHeight

    echo "${STREAM_WIDTH}" > functions/uvc.usb0/streaming/framebased/dfvi/480p/wWidth
    echo "${STREAM_HEIGHT}" > functions/uvc.usb0/streaming/framebased/dfvi/480p/wHeight

    # The links are not possible to have in the tar file
    cd functions/uvc.usb0/streaming/header/h || exit 1
    ln -s ../../uncompressed/yuv .
    ln -s ../../mjpeg/frame .
    ln -s ../../framebased/mjls .
    ln -s ../../framebased/dfvi .
    ln -s ../../header/h ../../class/fs/ || exit 1
    ln -s ../../header/h ../../class/hs/ || exit 1
    ln -s ../../header/h ../../class/ss/ || exit 1
    cd ../../../control || exit 1

    ln -s header/h class/fs
    ln -s header/h class/ss
    cd ../../../ || exit 1

    # Link everything up and bind the USB device.
    ln -s functions/uvc.usb0 configs/c.1
}
