#!/bin/sh
#
# Called from appcore when USB MSD function driver is changed
#

usage()
{
  echo "Usage: usbfn [<usbmode>]"
  echo "RNDIS           - ethernet function driver"
  echo "MTP             - media transfer function driver"
  echo "UVC             - video function driver"
  echo "RNDIS_MTP       - combined media transfer and ethernet driver"
  echo "UVC_MTP         - combined video function and media transfer driver"
  echo "RNDIS_UVC       - combined video function and ethernet driver"
  echo "RNDIS_UVC_MTP   - combined video function, media transfer and ethernet driver"
  echo
  echo "--help  - show this text"
}

if [ $# -eq 0 ]; then
    if [ ! -e /etc/usbmode ]
    then
	usage
	exit 0
    fi
    echo "$(cat /etc/usbmode 2>/dev/null)"
    exit
fi

if [ "$1" == "--help" ]; then
    usage
    exit 0
fi

USBMODE=$1
if [ "${USBMODE}" != "RNDIS" ] &&
   [ "${USBMODE}" != "MTP" ] &&
   [ "${USBMODE}" != "UVC" ] &&
   [ "${USBMODE}" != "RNDIS_MTP" ] &&
   [ "${USBMODE}" != "UVC_MTP" ] &&
   [ "${USBMODE}" != "RNDIS_UVC" ] &&
   [ "${USBMODE}" != "RNDIS_UVC_MTP" ]
then
    echo "Unknown USB mode ${USBMODE}"
    usage
    exit 1
fi
logger "USB function driver changed to ${USBMODE}"

if [ -d "/sys/kernel/config/usb_gadget/g1" ]; then
    CURRUSBMODE="$(cat /etc/usbmode  2>/dev/null)"
    if [ "$CURRUSBMODE" == "$USBMODE" ]; then
        echo "USBMODE ${USBMODE} already set"
        exit
    fi
fi

echo $USBMODE > /etc/usbmode
sync

export LD_LIBRARY_PATH=/FLIR/usr/lib
export PATH=$PATH:/usr/bin:/bin:/sbin:/FLIR/usr/bin

USBCMDRV="$(lsmod | grep -o '^usb_[a-z_]*')"
logger "USB composite driver loaded is ${USBCMDRV}"

gadget.sh unload

#indicate USB FN mode change
touch /var/lock/ufnchange

logger "New USB Composite driver is $usbmode"

#load desired USB function driver
gadget.sh load
sleep 2

rm /var/lock/ufnchange
