#!/bin/sh

case $1 in
    pre)
        sysctl kernel.panic_on_oops=1
        sysctl kernel.panic_on_warn=1
        sysctl kernel.panic=-1
        systemctl stop gadget
        systemctl stop bluetooth
        systemctl stop btload
        systemctl stop connman
        systemctl stop wpa_supplicant
        systemctl stop systemd-networkd
        modprobe -r qca9377
    ;;
    post)
        modprobe qca9377
        systemctl start systemd-networkd
        systemctl start wpa_supplicant
        systemctl start connman
        systemctl start btload
        systemctl start bluetooth
        systemctl start gadget
        sysctl kernel.panic_on_oops=0
        sysctl kernel.panic_on_warn=0
        sysctl kernel.panic=0
    ;;
esac
