#!/bin/sh
export LD_LIBRARY_PATH=/FLIR/usr/lib/
timeout=10000
case $1 in
    pre)
        /FLIR/usr/bin/rset -s -t $timeout .power.actions.prepareStandby true
        # Sleep added to let facets delayed standby have time to run
        sleep 0.5
        sysctl kernel.panic_on_oops=1
        sysctl kernel.panic_on_warn=1
        sysctl kernel.panic=-1
    ;;
    post)
        sysctl kernel.panic_on_oops=0
        sysctl kernel.panic_on_warn=0
        sysctl kernel.panic=0
        systemctl restart btload # load BT firmware to module
        # Added sleep for no communication with lepton until it has time to wake up
        [ "$(cat /etc/platform)" = "ec201" ] && sleep 1.0
        /FLIR/usr/bin/rset -s -t $timeout .power.actions.prepareResume true
    ;;
esac
