#!/bin/sh

case $1 in
    pre)
        systemctl stop gadget
        systemctl stop bluetooth
        systemctl stop btload
        systemctl stop wpa_supplicant
        systemctl stop connman
        modprobe -r qca9377
    ;;
    post)
        modprobe qca9377
        systemctl start connman
        systemctl start wpa_supplicant
        systemctl start btload
        systemctl start bluetooth
        systemctl start gadget
    ;;
esac
