#!/bin/sh

case $1 in
    pre)
        systemctl stop gadget
        systemctl stop bluetooth
        systemctl stop btload
        modprobe -r qca9377
    ;;
    post)
        modprobe qca9377
        systemctl start btload
        systemctl start bluetooth
        systemctl start gadget
    ;;
esac
